title: Prantik Roychowdhury
description: I am a highly driven, result-oriented proactive ML Engineer with work experience as an Intern at two companies. Currently I am looking
for an opportunity where I can utilize my knowledge and competently apply my skills to the fullest
show downloads: true
theme: jekyll-theme-minimal
